# Generated by Django 2.1.3 on 2018-12-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field=10, null=True, upload_to='', width_field=10),
        ),
    ]
