# Generated by Django 2.1.3 on 2018-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20181126_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ('content_eng', 'content_jp')},
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='content',
            new_name='content_eng',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='content',
            new_name='content_eng',
        ),
        migrations.AddField(
            model_name='sentence',
            name='content_jp',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='content_jp',
            field=models.CharField(default=None, max_length=63),
        ),
    ]
