# Generated by Django 2.1.3 on 2018-12-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20181127_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='ref',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='参考文献'),
        ),
    ]
