# Generated by Django 2.1.3 on 2018-12-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_auto_20181209_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='repetition',
        ),
    ]
