export const FETCH_BLOG_LIST = "FETCH_BLOG_LIST";
export const FETCH_BLOG_DETAIL="FETCH_BLOG_DETAIL";
export const FETCH_VOCABULARY_LIST = "FETCH_VOCABULARY_LIST";
export const FETCH_SENTENCE_LIST = "FETCH_SENTENCE_LIST";
export const RESET_BLOG_DETAIL="RESET_BLOG_DETAIL";
